#!/bin/sh

case $1 in
	clean)
		rm *.out *.a *.so core -f
		set +v
		;;

	build)
		if [ ! -f /usr/lib/libpl32.so ]; then
			echo "Error: pl32lib is not installed"
			exit 1
		fi
		cc -c -Iinclude src/file-io.c $FLAGS
#		cc -c -Iinclude src/net-io.c $FLAGS
#		cc -Iinclude src/main.c *.o $FLAGS
		rm *.o
		;;
	install)
		cp include/* /usr/include
		mv libpl32.* /usr/lib
		;;
esac
